### ISSUE TITLE
Faster Update

### ISSUE THREAD

**Issue by Reginald-Gillespie** [Infinite-Coder-001/Hotlist-API#3]
If you wanted faster updates, GAS (Google App Scripts) would be my choice. Then you can push the edited file to this repo. Github can have up to two hour's delay in it's cron Actions. There are some differences with the sway you fetch and everything, if you need help I can provide it but I think you can figure it out. You might find [this](https://gist.github.com/pamelafox/ea0474daa137f035b489bf78cc5797ea), from Pamela no less, interesting. Iirc you have up to 20K fetch requests per month using GAS, which is way more than enough to update even every minute.

Edit: Oh you turned on discussions, I should have used that.

~ Sprout

**Comment by Infinite-Coder-001** [comment]
I know, Github isn't the best. GAS look good, but I need to run the update.py file and I don't know, how to run python there. Why are all files .gs? What does it mean?

**Comment by Reginald-Gillespie** [comment]
`.gs` stands for "Google Script", it's basically a spin-off of node.js, which is a server runtime for javascript. So for all your purposes it's just javascript with their own APIs.

You don't run the update.py file. On github, you write to the files as if you are running inside the repo. When you're not running inside github, you can just push an edit to the file directly. Or at least, I assume. I know it can be done, but I haven't done it myself yet. With enough research you should be able to figure it out though.

**Comment by Infinite-Coder-001** [comment]
My problem isn't to write to files on Github, I use the update.py file to load data from KA hotlist. It would be better, if there would be a way to run the python file, because if not, I would have to write the whole script again in node.js. I don't like node.js very much, it's so hard to do there such a simple thing like websrapping. I spent above 5 hours finding a server, where I can run my python script, then I finally found this, I don't want to do it whole again :( If you know any server, where I can also run the python file, please tell me. Thanks.

**Comment by Reginald-Gillespie** [comment]
So first of all, yes, you would have rewrite in in javascript.
HOWEVER, you're using selenium, which is an overcomplicated library, and you don't need it. Ditch it, and work with requests directly. It will be much faster, reliable, and all the rest. 

Open DevTools, then click the networking tab. Go to `https://www.khanacademy.org/computing/computer-programming/browse`. Filter the requests so that instead of "All" it just shows "Fetch/XHR" requests (API requests). Everything there are the API requests to the server for information. The one starting with `hotlist?lang=en&_=` is the one for the hotlist data. Click it and read the response. The `{}` in the bottom left will parse it to make it more readable. Requesting this endpoint directly is much faster than using selenium.

You can right-click the request and click "Copy as fetch" (make sure it's the right one). Paste it into a text editor. That's the request to get the HL, in node. Most of the headers and stuff in this case are default browser stuff that you don't need, you just need the method and body. Here's how to get the HL response from the API endpoint in python (even though python sucks):

```python
import requests

url = 'https://www.khanacademy.org/api/internal/graphql/hotlist'

json = {"operationName":"hotlist","query":"query hotlist($curationNodeId: String, $onlyOfficialProjectSpinoffs: Boolean!, $sort: ListProgramSortOrder, $pageInfo: ListProgramsPageInfo) {\n  listTopPrograms(curationNodeId: $curationNodeId, onlyOfficialProjectSpinoffs: $onlyOfficialProjectSpinoffs, sort: $sort, pageInfo: $pageInfo) {\n    complete\n    cursor\n    programs {\n      id\n      key\n      authorKaid\n      authorNickname\n      displayableSpinoffCount\n      imagePath\n      sumVotesIncremented\n      translatedTitle: title\n      url\n      __typename\n    }\n    __typename\n  }\n}\n","variables":{"curationNodeId":"xffde7c31","onlyOfficialProjectSpinoffs":False,"sort":"HOT","pageInfo":{"itemsPerPage":30,"cursor":""}}}

response = requests.post(url, json = json)
print(response.text)
```

In GAS to fetch you just replace `fetch` with `UrlFetchApp.fetch` and `body` with `payload`.

Never use selenium unless the page has HEAVY javascript use that you don't feel like reversing.

**Comment by Reginald-Gillespie** [comment]
My account was banned for ban evasion, so if you need help you'll need to ask me here.

**Comment by Infinite-Coder-001** [comment]
Oh, that's sad. What did you do? Was it something with your API? Can I help you?

**Comment by Reginald-Gillespie** [comment]
I did nothing, it wasn't anything with the API, and you can't help me considering KA doesn't listen to people asking for others to be unbanned. I made an American flag program (red+blue+green stripes lol) something like a year ago and was banned for that, my main is @WKoA not that you can see anything.

**Comment by Reginald-Gillespie** [comment]
`Eh` is my account and what I said is a legitimate security concern. Easiest way to avoid it is to encode in url encoding or base64 or some form like that before writing it to the array. I think I'd probably encode each entity individually, and then decode in KA, or you could probably transmit it as a string and then decode all at once on KA.

**Comment by Reginald-Gillespie** [comment]
Here's my GAS code so far:

Here's the main file, and then create a new .gs file in the same project called GittubClient.gs, the code for that is here: https://gist.github.com/mvl/356be3063026dce6c44d457227b8e167

You will need to create a Personal Access Token (PAT) and check the "repo" scope to allow it to push updates.

```js
function update(code) {
  var {
    BuildTree,
    Commit,
    SetBranch,
    GetBranches
  } = this.GitHub({
    owner: "Reginald-Gillespie",
    repo: "GASImpots",
    username: "Reginald-Gillespie",
    // branch: "main",
    token: "PAT"
  })
  console.log("Main branch found: " + SetBranch("main"));
  var result = Commit(
    BuildTree("import.js", code),
    "Reginald-Gillespie", "reginaldgillespie@protonmail.com"
  ); 
  console.log("Committed: " + result);
}
function getHL() {
  var HL = UrlFetchApp.fetch("https://www.khanacademy.org/api/internal/graphql/hotlist", {
    "payload": "{\"operationName\":\"hotlist\",\"query\":\"query hotlist($curationNodeId: String, $onlyOfficialProjectSpinoffs: Boolean!, $sort: ListProgramSortOrder, $pageInfo: ListProgramsPageInfo) {\\n  listTopPrograms(curationNodeId: $curationNodeId, onlyOfficialProjectSpinoffs: $onlyOfficialProjectSpinoffs, sort: $sort, pageInfo: $pageInfo) {\\n    complete\\n    cursor\\n    programs {\\n      id\\n      key\\n      authorKaid\\n      authorNickname\\n      displayableSpinoffCount\\n      imagePath\\n      sumVotesIncremented\\n      translatedTitle: title\\n      url\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\",\"variables\":{\"curationNodeId\":\"xffde7c31\",\"onlyOfficialProjectSpinoffs\":false,\"sort\":\"HOT\",\"pageInfo\":{\"itemsPerPage\":30,\"cursor\":\"\"}}}",
    "method": "POST",
    "mode": "cors",
    "credentials": "omit"
  });
  return JSON.stringify(HL.getContentText());
}
function run() {
  var lastHL = PropertiesService.getScriptProperties().getProperty("HL");
  var HL = getHL();
  var file = `var HL = "${encodeURIComponent(HL)}"`;
  update(file);

  if (file !== lastHL) {
    console.log("Purging jsdelivr cache")
    UrlFetchApp.fetch("https://purge.jsdelivr.net/gh/Reginald-Gillespie/GASImpots@main/import.js")
    PropertiesService.getScriptProperties().setProperty("HL", file);
  }
}
```

I'm having trouble atm decoding the URL-encoded response, so good luck figuring that out =P
Escaping like you did yours is probably fine.
But everything else works.

**Comment by Infinite-Coder-001** [comment]
So I replace the 'token: "PAT"' with with my github token? 
PS: I looked at your code, purging Jsdelivr's cache isn't the best. Somebody can code a bot, that will spam purging the cache and you will get throttled. You should use a timestamp - just add a timestamp to the file name - look at my current python code.

**Comment by Reginald-Gillespie** [comment]
Yup. Go to Settings > Developer, and create a legacy token with the role checked.

True, someone could bot it, that's a good point. Adding url params of a random number might be better than timestmaps if that works for jsdelivr (it works sometimes for preventing caching but not tested on jsdelivr). I could see some issues getting timestamps to line up right, like if your clock is off, so I would check all that. I didn't want to get into that right away which is why I purged it.

**Comment by Infinite-Coder-001** [comment]
Okay. The requests work nice, I'll just change some things and it'll be done. Thank you so much :) I'll give you credit. 

Adding params is a good idea, I'll test it, but timestamps work almostly always.

**Comment by Reginald-Gillespie** [comment]
Thanks, it was nice to be able to be the start of a hopefully new trend of API =P

Timestamps work better if you update ever 5-10 minutes, when you're going every minute it could be hard. Actually though, if url params don't work, you could push 5 files, covering each minute to the side of it in case someone is slightly off.

**Comment by Infinite-Coder-001** [comment]
It works, but after 1080 updates per day, it says: 
```Exception: Service invoked too many times for one day: urlfetch. ```
There's probably a limit :( So I would have to run it every 10 minutes anyway.

**Comment by Reginald-Gillespie** [comment]
Oh it does? I run a project every minute and haven't have any issues. Then again it only does one fetch... this one needs to fetch again for github. Some things like the branch fetch and all that you don't actually need, I bet you could get it down low enough to last all day.

**Comment by Infinite-Coder-001** [comment]
I have a gmail account. I don't have any other projects. I write 3 files per minute, because I decided to load more pages from hotlist, but still, it shouldn't break the limit. The project was running from midnight to 6 o'clock.

**Comment by Reginald-Gillespie** [comment]
Instead of making more fetches to get more pages from the HL, you can set the program limit higher in the payload. Scroll to the end and change `itemsPerPage` to 90 or something. Then check the github code and see if you can just not set the branch it goes to, I don't think that actually needed. Did you accidentally set multiple one-minute triggers or something? Because you should not have come anywhere near the quota

**Comment by Infinite-Coder-001** [comment]
I changed itemsPerPage already before. Yes, I did 3 requests, now I changed it to 1, but I don't understand, why it ran out of quota.

**Comment by Reginald-Gillespie** [comment]
Yeah, nor do I. Could I see the code? Either send the code directly (after removing tokens) or if you have it running on an email you can share you could set the project to viewable to anyone with the link

**Comment by Infinite-Coder-001** [comment]
This is my main code: 
```
function update(file, code) {
  var {
    BuildTree,
    Commit,
    SetBranch,
    GetBranches
  } = this.GitHub({
    owner: "Infinite-Coder-001",
    repo: "Hotlist-API",
    username: "Infinite-Coder-001",
    // branch: "main",
    token: "MY-GITHUB-TOKEN"
  })
  //console.log("Main branch found: " + SetBranch("main"));
  SetBranch("main");
  var result = Commit(
    BuildTree(file, code),
    "Infinite-Coder-001", "markusatko@gmail.com"
  ); 
  //console.log("Committed: " + result);
}

var loadPrograms = 100;

function getHL() {
  var HL = UrlFetchApp.fetch("https://www.khanacademy.org/api/internal/graphql/hotlist", {
    "payload": "{\"operationName\":\"hotlist\",\"query\":\"query hotlist($curationNodeId: String, $onlyOfficialProjectSpinoffs: Boolean!, $sort: ListProgramSortOrder, $pageInfo: ListProgramsPageInfo) {\\n  listTopPrograms(curationNodeId: $curationNodeId, onlyOfficialProjectSpinoffs: $onlyOfficialProjectSpinoffs, sort: $sort, pageInfo: $pageInfo) {\\n    complete\\n    cursor\\n    programs {\\n      id\\n      key\\n      authorKaid\\n      authorNickname\\n      displayableSpinoffCount\\n      imagePath\\n      sumVotesIncremented\\n      translatedTitle: title\\n      url\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\",\"variables\":{\"curationNodeId\":\"xffde7c31\",\"onlyOfficialProjectSpinoffs\":false,\"sort\":\"HOT\",\"pageInfo\":{\"itemsPerPage\":" + String(loadPrograms) + ",\"cursor\":\"\"}}}",
    "method": "POST",
    "mode": "cors",
    "credentials": "omit"
  });
  return JSON.parse(HL.getContentText());
}
function run() {
  var HL = getHL();
  //console.log(HL.data.listTopPrograms.programs.length);

  var date = new Date(Date.now());
  var year = date.getUTCFullYear();
  var month = date.getUTCMonth();
  var day = date.getUTCDate();
  var hours = date.getUTCHours();
  var minutes = date.getUTCMinutes();

  if (String(month).split("").length === 1) {
    month = "0" + String(parseInt(month) + 1);
  }
  if (String(day).split("").length === 1) {
    day = "0" + day;
  }
  if (String(hours).split("").length === 1) {
    hours = "0" + hours;
  }
  if (String(minutes).split("").length === 1) {
    minutes = "0" + minutes;
  }
  
  var programs = "[";
  for (var i = 0; i < 100; i ++) {
    programs += "\n    {\n      title: '" + HL.data.listTopPrograms.programs[i].translatedTitle.replace("\\", "\\\\").replace("'", "\\'").replace("<", "&#60;") + "', \n      author: '" + HL.data.listTopPrograms.programs[i].authorNickname.replace("\\", "\\\\").replace("'", "\\'").replace("<", "&#60;") + "', \n      votes: " + String(HL.data.listTopPrograms.programs[i].sumVotesIncremented) + ", \n      forks: " + String(HL.data.listTopPrograms.programs[i].displayableSpinoffCount) + ", \n      thumbnail: '" + HL.data.listTopPrograms.programs[i].imagePath + "', \n      link: 'https://www.khanacademy.org" + HL.data.listTopPrograms.programs[i].url + "', \n      authorLink: 'https://www.khanacademy.org/profile/" + HL.data.listTopPrograms.programs[i].authorKaid + "'\n    }, ";
  }
  programs += "\n  ];"
  programs = "var LoadHotlistAPI = function() {\n  return " + programs + "\n};"

  update("new-api/new-api-" + String(year) + String(month) + String(day) + String(hours) + String(minutes) + ".js", programs);
  

  console.log("DONE")

  //var file = `var HL = "${HL}"`;
  //update(file);
}
run();
```

Then, I created the GithubClient.gs file, where I put the code from https://gist.github.com/mvl/356be3063026dce6c44d457227b8e167

**Comment by Reginald-Gillespie** [comment]
So you're only making 1 fetch... huh.
I found that setting the branch does take I believe one request, which can be removed. 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/109245101/224551981-4f1e8a01-e444-4c6e-8070-0dc58b0f90d4.png">
So I made the Github client log each time it made a request, and it makes 4 requests per commit (not including setting branch). I suppose if you wrote to 3 files, that would make 15 requests per run (assuming you set the branch each time you wrote to a new file). So it would have run out if you did it each minute for the entire day, but not just part of the day...

idk, I would change it to only update once, not set the branch if that still works, and run it all day to see if it has errors

**Comment by Infinite-Coder-001** [comment]
Okay. So I'll just wait.

**Comment by Reginald-Gillespie** [comment]
Or create a new gmail with a fresh quota lol

**Comment by Infinite-Coder-001** [comment]
Lol, yes.

**Comment by Infinite-Coder-001** [comment]
# I finally did it!
The script is running 24 hours with no break. I released version 1.6.0, look on KA. Thanks so much!

**Comment by Reginald-Gillespie** [comment]
Noice, I saw it. Be careful about putting links like JSdelivr in ka because it sometimes hides it, but I've verified that it is still there so you're good.

**Comment by Infinite-Coder-001** [comment]
Yes, I already know, because I was trying to send a message before. I've sent it 10 times and I was surprised, that nobody answered. But Khan Academy said, that all messages were sucessfully sent XD 

And thanks, is there anything else, that you'd like to discuss?

**Comment by Reginald-Gillespie** [comment]
Yeah KA says it went through, you can open it in incogneto to check if you're unsure. The LQ score was 21 (typically anything over 2 is hidden) but either KA has an exception for some urls like jsdelivr links or a possibly a guardian approved it.

Not atm. Obviously if you add more endpoints using this method you'll need more google accounts if they're going to be updating every minute. Maybe you could make a program showing other's how to implement it into their google account. If you had a turn server you could have them submit the body to the server, and then have it write the response to github, solving jsdelivr cache issues and things being a minute behind, but I don't think you have the hardware for that now considering it takes a server with a public IP to be on 24/7. 

If you have ideas or questions about the API you can open up an issue under a random one of my projects (one of my khan ones is best).

**Comment by Infinite-Coder-001** [comment]
Okay. I can have as many accounts on Google as I want. I can make a bot, that will create Google accounts 😆 I don't know, what do you exactly mean in the second paragraph. How would you solve the cache issues? Timestamps work good for me. But if there's a better method, I'll use it. 

So should I close this issue or can I keep it open?

**Comment by Reginald-Gillespie** [comment]
I don't think you (or even I) could tbh, they have high security, unlike KA =P. By the 2ndish account you'd be flagged.

Timestamps are good. Just saying a turn server would solve the 2% of times where timestamps would have issues (i.e. client device clock is set custom and is wrong)

Whatever you want. You can keep it open or I can go sub to a discussion thread here if you don't like having the issues tab say there's one open =P

**Comment by Infinite-Coder-001** [comment]
But they don't have any verification, maybe just recaptcha, when it detects unrecognized device. 

Well, I don't have a turn server. I put in the code, that when a file fails to load, it loads the file from previous minute and if it fails again, it loads the file before 2 minutes etc. But I also put there a loop protection, so it has only ~100 attempts. 

I can convert this to discussion.

**Comment by Infinite-Coder-001** [comment]
@Reginald-Gillespie I've read through this whole thread again and noticed that some of my replies were really rude. I'd like to apologize for that - I'm very sorry.
I appreciate your help on this project. You taught me a lot of useful new programming techniques I previously had no clue about. 
Thanks for your patience with me; I know it sometimes isn't easy :)

**Comment by Reginald-Gillespie** [comment]
Oh you're good. I'm not going to read the thread again but I can be the same at times.
